export enum ExperienceLevel {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  EXPERT = 'EXPERT',
}

export enum Availability {
  OPEN = 'OPEN',
  BUSY = 'BUSY',
}

export enum Skills {
  LEGAL_RESEARCH = 'LEGAL_RESEARCH',
  LITIGATION_SUPPORT = 'LITIGATION_SUPPORT',
  DISCOVERY = 'DISCOVERY',
  PLEADINGS = 'PLEADINGS',
  INTELLECTUAL_PROPERTY = 'INTELLECTUAL_PROPERTY',
  BUSINESS_FORMATION = 'BUSINESS_FORMATION',
  MEMOS = 'MEMOS',
  REAL_ESTATE = 'REAL_ESTATE',
  CONTRACTS = 'CONTRACTS',
  BRIEFS = 'BRIEFS',
  LEGAL_CONSULTATION = 'LEGAL_CONSULTATION',
}
